### ISSUE TITLE
UserStatistics assumes that threadNo is unique; it is not, must be changed to include boardCode

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#108]
ThreadNo is specific to each board, you can have the same threadNo on different boards and it will be a different thread.  UserStastitics needs to be changed to reflect this.

**Comment by grzegorznittner** [comment]
Are you sure? I think I assumed in many places that thread ids are unique
across the site.

**Comment by johnarleyburns** [comment]
They aren't, try it out, you can see its an ascending sequence unique to
each board.

**Comment by johnarleyburns** [comment]
Lots of fixes today, you may have to clear cache before board loading
works, I have that problem sometimes when I change the ChanPost.

**Comment by grzegorznittner** [comment]
Implemented but not pushed yet. Needs testing. Class methods are not modified.

**Comment by johnarleyburns** [comment]
One way to test is to view 5 images on a thread and see if it auto-adds to
watchlist with popup message

**Comment by grzegorznittner** [comment]
Fixed. All data automatically corrected.

**Comment by johnarleyburns** [comment]
nice
