### ISSUE TITLE
Full screen gallery view needs contextual menu re-added

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#136]
Should be able to copy/paste from full screen image activity

**Comment by grzegorznittner** [comment]
Contextual menus seems not working with GLSurfaceView.
I've added old contextual menu to the option menu. It's available only when image is loaded.
I think this could be even clearer for the user that there is only one possible context in which menu is displayed on FullImageView.
@johnarleyburns  What do you think about that?

**Comment by johnarleyburns** [comment]
The reason it was contextual is that this is the default behavior in web
view and probably what users are used to.  But the main problem now is that
gallery keeps crashing and I can't scroll through images.

On Mon, Feb 11, 2013 at 12:56 AM, Grzegorz Nittner <notifications@github.com

**Comment by grzegorznittner** [comment]
Is it still crashing after my last changes? Have you clean/build gallery and our app?

Dnia 11 lut 2013 o godz. 20:03 John Burns notifications@github.com napisał(a):

**Comment by johnarleyburns** [comment]
Yes, same behavior on SIII, is it better on Note?  I just go to full view
and then click next to view, it generally crashes on the 5th image or so.

On Mon, Feb 11, 2013 at 10:52 PM, Grzegorz Nittner <notifications@github.com

**Comment by grzegorznittner** [comment]
I've tested on LG, htc, nexus 7 and galaxy note 2.
Do you see extended option menu on full image view?

Dnia 11 lut 2013 o godz. 23:08 John Burns notifications@github.com napisał(a):

**Comment by johnarleyburns** [comment]
Is there a way to run command line build?
