### ISSUE TITLE
Animated gifs don't work in new gallery

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#143]
no animation occurs, downloading same gif via web and viewing in standard gallery works

**Comment by mirceapopro** [comment]
The Gallery introduced by Grzeg is using BitmapRegionDecoder to display, resize the image. it does not support animation so unless we change to something else...

**Comment by johnarleyburns** [comment]
Either GifDecoder or WebView is necessary.
http://droid-blog.net/2011/10/15/tutorial-how-to-play-animated-gifs-in-android-%E2%80%93-part-2/
