### ISSUE TITLE
Gallery is not loading full images (sometimes)

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#167]
Happened on Nexus 7.
Go to wg board. Select thread with lots of images large images (almost any).
Thumbs are loaded but first image become resized thumb, it's not refreshed.

**Comment by johnarleyburns** [comment]
Yes i noticed this too.

On Fri, Feb 22, 2013 at 12:07 PM, Grzegorz Nittner <notifications@github.com

**Comment by grzegorznittner** [comment]
I think that Gallery tries to preload to many images the same time, it
takes too much time and resized thumbnail is not replaced.

**Comment by johnarleyburns** [comment]
fixed in previous commit
