### ISSUE TITLE
Gallery doesn't persist last location

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#169]
Scroll to n-th image in the gallery, then change screen orientation.

**Comment by johnarleyburns** [comment]
Easy way to do this I use on threadactivity is to save the last position in
onPause and then move to it in onResume

On Fri, Feb 22, 2013 at 12:39 PM, Grzegorz Nittner <notifications@github.com

**Comment by johnarleyburns** [comment]
Also doesn't appear to set the bottom-scroll position when first going into gallery - it just always shows the beginning.
