### ISSUE TITLE
download all images isn't implemented

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#20]
the functionality isn't implemented, ideally do it as mimichan and display a grid view with all the thumbnail images (like hideAllText view) but with little checkboxes on each one to select which to download, i think there's some android api for this, then download / copy the full size to a custom gallery location (let the user pick or make a new one).

this is a big requested feature and important to get right.

**Comment by grzegorznittner** [comment]
needs to be done: 
- handling properly offline mode
- cancelling that task
- allow to select images for download
- icon needs to be created
