### ISSUE TITLE
Galley slideshow shows thumbnails even when images are available

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#201]
Sometimes gallery slideshow shows thumbnails even when images are available, I can go into the photo view, everything has downloaded, I can see the image, but thumbnail still shows up with no full image view during slideshow, happens randomly for image, seems like maybe related to timing?

**Comment by grzegorznittner** [comment]
Played with slideshow for 30min and couldn't reproduce the issue on HTC One.

**Comment by johnarleyburns** [comment]
I'm not seeing either.  I think it was an artifact of calling
prepareGalleryView before thread was loaded, which is now avoided.
