### ISSUE TITLE
Threads marked dead too quiclky

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#206]
Just played a bit with app and i got annoying
behaviour for threads:
1. Went to adv board
2. My connection went offline
3. I opened thread, of course only first post there.
4. Added thread to watched list
5. I had to restart phone (Probably not relevant)
6. Opened thread from watched list, got message
"thread marked as dead"
7. Then went back to adv and i noticed that this
thread has 157 replies, opened it, see only one
post but in header it's written 157
8. Tried refresh but it's not working as thread is
marked as dead

Also, thread disappeared from watched list

**Comment by grzegorznittner** [comment]
The main issue is that we don't load full thread when it's marked dead.
Not sure if i want to have my watched list cleared without beeing asked about that. We can sent notification "your watchlist needs attention", then list threads for deletion.

**Comment by johnarleyburns** [comment]
now configurable with pref, defaults to 30 days
