### ISSUE TITLE
Watchlist thread info is missing on add thread

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#212]
When adding a watchlist from a board (Japanese Culture for instance), the thread gets added with boardCode and threadNo, but the subject, text, num replies, all other info is missing.

**Comment by grzegorznittner** [comment]
One thing i'm 100% sure, current watchilist board is stored in a wrong way:
- threads data are not stored
- 7 watched threads generated 1MB of json

needs to be redesigned

**Comment by grzegorznittner** [comment]
Fixed
