### ISSUE TITLE
Tutorial "last showed" time is not updated

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#251]
Go to page which will display tutorial page, then click "back" button, then make the same action again, tutorial page is displayed, but it shouldn't.

Might be also related, but the following click path displayed tutorial again:
- go to thread view so tutorial is displayed
- instead of clicking "got it" click on search, type search term and do a search
- then click "got it"
- click "back" button
- tutorial is displayed (same as previously), even i've already clicked "got it" for that page

**Comment by johnarleyburns** [comment]
I think onresume needs to recheck tutorial status
