### ISSUE TITLE
Search requires two click to perform search

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#253]
If you click search on thread view a search field is displayed with "X" to clear it.
To enable filter you need to click twice on carriage return button, which is not an obvious choice. We need to have a search button or something like that.
I'd say that "X" is less important than "search" button, maybe we can replace "X" with "magnifier" icon and use it to trigger search.

**Comment by johnarleyburns** [comment]
added "triangle" button next to "X" for clicking to trigger search
