### ISSUE TITLE
Thread view - when image expansion fails you can't go to gallery

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#262]
After clicking on thumb I got message "can't load image: out of memory".
First, message is not usefull for user.
Second, I wasn't able to click on thumb to go to gallery. After first fail click on thumb should open gallery view.

**Comment by johnarleyburns** [comment]
left click after first fail so user can try to download again
added "images" link so you can click directly to gallery from board view

**Comment by johnarleyburns** [comment]
also fixed so that if failure happens and you click it goes to gallery album view
