### ISSUE TITLE
Popular page doesn't auto reload

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#265]
After app installation I lost network connection, but i started chanu. I got almost empty popular page. This is not right behaviour, we should display something here, maybe tutorial, at least explanation why this page is empty.

I configured my connection again, but popular page has not autoreload. Something was blocked there as even manual refresh has not updated the page.

**Comment by johnarleyburns** [comment]
reload property works now, not sure about fresh install, please test
