### ISSUE TITLE
implement pull to refresh for android action bar board and thread manual refresh

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#273]

**Comment by grzegorznittner** [comment]
i'm still a bit resistive to that pull to refresh thing
the main issue is that data fetch takes some time, i don't think user
should take additional action to initiate data fetching
for me it's more convinient to show user that there are new posts/updates
available, especially that we are going to keep auto fetching in some cases

the most i like that idea with refresh button with indicator how many new
posts/updates are available, in this case refresh will work as UI update
only when items are available, and as force refresh when nothing is there

**Comment by johnarleyburns** [comment]
implemented, but kept existing refresh button in overflow
