### ISSUE TITLE
Board view doesn't persist location

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#286]
If you come back from thread view you always see top of the board view.

**Comment by grzegorznittner** [comment]
It does work when you click back button. Only action bar back doesn't work, you always go to the top of board.

**Comment by johnarleyburns** [comment]
I'm not sure in this case if we should preserve the location

**Comment by johnarleyburns** [comment]
fixed a case where it was reset when you tried to scroll after clicking back
