### ISSUE TITLE
Devise new name for 4channer app

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#30]
To comply with terms of service, we can't have "4chan" in the name, so we need something new.  Ideally something short and unused like "Kodak".   A few I found with no trademark:

Chano
Chanu
Chane
Imgo
Mewin

**Comment by grzegorznittner** [comment]
What about chan4you

**Comment by johnarleyburns** [comment]
Too long

**Comment by johnarleyburns** [comment]
Put this one on hold until we see if we can do some official sponsorship
