### ISSUE TITLE
Images button on thread view shows only 1 image even texts says XXX images

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#312]
Happened couple of times to me.
Went to thread view, i see "172 images", then I click on this (before thread loads) and gallery shows only 1 image.

**Comment by grzegorznittner** [comment]
Maybe we can make "XXX images" button clickable after thread is loaded.

**Comment by johnarleyburns** [comment]
This is a general problem if you visit gallery before thread is loaded and
parsed.  I think gallery should check if the thread is loaded, if it's not
(if it finds defdata) then check if loading is happening in background, and
if not then kick it off.  ThreadFragment does something similar.

On Tue, Aug 27, 2013 at 10:37 PM, Grzegorz Nittner <notifications@github.com

**Comment by johnarleyburns** [comment]
now gallery view waits on thread to load if not with no connection, also can be jumped to directly from board level card view
