### ISSUE TITLE
Screen remains empty for long time as thread is fetched

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#313]
I left chanu open in gallery. After some time I came back and clicked upper back button. Thread view was opened but empty, even previously data were available.
I think currently we always reload after certain time which, on slow connection, may cause empty page for long time. For users it may be very annoying.

**Comment by johnarleyburns** [comment]
yes we do that to avoid "flash" when page is reloaded

instead we should check health and set a timer, then load old data if new
data isnt coming fast

**Comment by johnarleyburns** [comment]
fixed, now always pre-loads first thread from board as before, avoids flashing with data notification

**Comment by johnarleyburns** [comment]
also fixed for gallery up button not reloading thread unnecessarily
