### ISSUE TITLE
References view contains link to images which doesn't work

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#314]
Only happens when references contain first post which contains button to images.
I think that button should not be clickable in references view.

**Comment by johnarleyburns** [comment]
What is "References View"?  I'm confused.

On Wed, Aug 28, 2013 at 11:18 PM, Grzegorz Nittner <notifications@github.com

**Comment by grzegorznittner** [comment]
When you click on the post number you see a popup window which says
"References" ;)

**Comment by johnarleyburns** [comment]
naprawiony
