### ISSUE TITLE
try for smaller and center cropped gallery view

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#366]

**Comment by grzegorznittner** [comment]
Images for thumbnails and album view center cropped.
Size of gallery is defined in resources, if we want to change we need to decide how many rows we want per each device category.

**Comment by johnarleyburns** [comment]
okay we can play around, basically 1.5 or 2x the number of rows should be
good

**Comment by grzegorznittner** [comment]
I added one row to each gallery view. Images are now center cropped.
