### ISSUE TITLE
GIF loading problem

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#389]
As others mentioned, some gifs do not load. From my particular experience it's generally the first 2 gifs of any thread. Surfed around in /gif/ and found this to occur repeatedly, at least on my phone.

**Comment by grzegorznittner** [comment]
Gif issues caused by expanding gif in thread view. Unfortunately to fix that I'll have to modify ImageLoader which I don't want now. For now gif is reloaded when file size is much smaller than fsize param of the post.

All gifs displayed via webview so it should work now.
