### ISSUE TITLE
Long threads often never display

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#39]
Go to an active board like /b or /v and find a thread with 400+ posts, often the board will simply not display

**Comment by grzegorznittner** [comment]
Tested with threads having 300+, 400+ and even 502 posts. First header posts are shown (3 to 6 depends on thread), in background the whole thread is loaded it takes some time (depends on connection), on WiFi 502 posts were loaded in less than 5s.
The only problem which I noticed was about refresh times. Increased forced refresh times. Probably I'll need to introduce new type of fetch delay.
