### ISSUE TITLE
Support downloads of images and threads directly from gallery

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#395]

**Comment by grzegorznittner** [comment]
this is kind of stupid, in gallery images are already downloaded (full size)
you should be able to select images to download from thread view, those
images are thumbnails

**Comment by johnarleyburns** [comment]
What it means is that people often want to "save" images into gallery as
long-term storage.

On Fri, Sep 13, 2013 at 10:41 PM, Grzegorz Nittner <notifications@github.com

> wrote:
> 
> this is kind of stupid, in gallery images are already downloaded (full
> size)
> you should be able to select images to download from thread view, those
> images are thumbnails
>

**Comment by grzegorznittner** [comment]
Then we need to add a button to the gallery view which will copy image from
our internal storage to the gallery.
Button like "play" but in the corner.

**Comment by johnarleyburns** [comment]
Could also be in the overflow menu

**Comment by grzegorznittner** [comment]
If you go to gallery album from the thread, via large button "XX images", you see grid of thumbs, you can select/multiselect them and share. We can add an option "Store in Gallery" or something like that. What do you think?

**Comment by johnarleyburns** [comment]
yes i think 'save to gallery' or 'archive to gallery', would also give us
one of the few lacking features that mimichan has.
