### ISSUE TITLE
Gift codes to enable full version

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#397]
Would be nice to be able to activate full version by gift code.
But we need to be carefull to not enable backdoor for all users

**Comment by johnarleyburns** [comment]
Google Play doesn't support coupon codes yet, it's a planned future feature.

On Fri, Sep 13, 2013 at 11:03 PM, Grzegorz Nittner <notifications@github.com

**Comment by johnarleyburns** [comment]
will re-open when it's made possible, however we can also put their email address into the dev console and will accomplish the same thing.
