### ISSUE TITLE
Download all images to zip file

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#42]
I've noticed some threads where people ask for a zip file of all threads, a menu item should exist to zip all images and then use our existing "Share" functionality to allow them to send the zip to their email or wherever or save it on the sd card.

**Comment by grzegorznittner** [comment]
After selecting that function a popup will appear:
- Save to:
  - zip file named: &lt;text field for the file name&gt;
  - gallery in folder: &lt;text field for folder name&gt;

Task will be executed in background. When finished user will get notification. Not sure if we'll be able to allow user share that file at that time.

**Comment by johnarleyburns** [comment]
Zip file isn't needed, I've used the standard gallery to send a bunch of images to email, elsewhere, it works fine.
