### ISSUE TITLE
Proprietary Software keeping Chanu out of F-Droid

### ISSUE THREAD

**Issue by yate** [grzegorznittner/chanu#421]
I saw this topic at f-droid https://f-droid.org/forums/topic/chanu-4chan-app/.  

I'm guessing libGoogleAnalyticsV2.jar is the propriety jar?  Is removing this an option? 
Is getting the app on f-droid a goal for you guys?

**Comment by johnarleyburns** [comment]
yes a goal
it should be easily removable only one class does the analytics

**Comment by yate** [comment]
This means getting rid of billing/purchasing of pro keys?

**Comment by johnarleyburns** [comment]
yes

**Comment by yate** [comment]
https://f-droid.org/forums/topic/chanu-4chan-app/#post-12742

**Comment by johnarleyburns** [comment]
Thanks!

**Comment by ghost** [comment]
Where did nineoldandroids-2.4.0.jar come from? It doesn't match the signature of the upstream package from https://github.com/JakeWharton/NineOldAndroids/downloads and replacing it with a version build from the latest upstream sources throws missing resource errors...

**Comment by yate** [comment]
@krt16s I've submitted a pull request with the official jar. I think the missing resource errors were because the project needs to be built on the ui-experimental branch currently.  Were you building on master?

**Comment by johnarleyburns** [comment]
Please re-pull, we've merged in the upstream version and it passes travis
ci on the ui-experimental branch.

**Comment by ghost** [comment]
Should be build tonight.

**Comment by yate** [comment]
https://f-droid.org/repository/browse/?fdfilter=chanu&fdid=com.chanapps.four.activity

Awesome! Thanks @krt16s

**Comment by johnarleyburns** [comment]
Noticed a bug, I should remove the BILLING permission from the APK manifest
file, also I think the android version number should be updated to avoid
conflicts.

**Comment by yate** [comment]
I have the billing permission removed from the memory-leaks pull request, i probably should have done a new one for that.

**Comment by ghost** [comment]
We try not to pull already deployed, working builds, so a version bump would be appreciated.

**Comment by johnarleyburns** [comment]
Yes, we need to version bump any time we do a charge, also in the android
manifest, I'm not sure if there's a way to automate it.

**Comment by yate** [comment]
Maybe a script like `./chanu-release.sh 2.0.4` which would change the numbers/date in version.xml (increment the code, name = 2.0.4, todays date), commit it, create a tag (2.0.4), then push the tag to the repo, which would trigger a travis deploy?

**Comment by johnarleyburns** [comment]
We also need to update the AndroidManifest.xml at the same time.  Now it's
version 1.78, but we could make it 2.0.4 to keep in sync.  Also there is a
section in the About screen which should also be synced, so the user knows
what version they have.

**Comment by yate** [comment]
It looks like both the manifest and the about screen use @string/versionName from version.xml. The manifest is using it's own version code though so we can probably change it to @string/versionCode, then it's all in one place.

**Comment by johnarleyburns** [comment]
Unfortunately the manifest won't interpolate the @string values, so it has
to be duplicated in both places.
