### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by yate** [grzegorznittner/chanu#423]
I've set up Travis CI on my fork and have gotten the build working on it.  It would be helpful to know that the project can build with pure ant and on any system, especially if f-droid is going to be building it.  I also consolidated the Gallery source folders into just one src folder, if you'd like I can undo that.

All it would require to set up is signing in with your github account https://travis-ci.org/, turning on the chanu build in your account page, and pointing the build status in the README to the real chanu's build (right now its pointing to mine)

What are your thoughts?

**Comment by johnarleyburns** [comment]
Greg can you follow these steps?  I tried but since you're the official
owner of the Chanu repository, only you are authorized to do it.

**Comment by grzegorznittner** [comment]
Done

**Comment by johnarleyburns** [comment]
all right hopefully f-droid will like it better

**Comment by johnarleyburns** [comment]
Can you post the link to travis ci, share it with me or something?  I can't
see the travis ci link.  I want to post the built APK for f-droid so they
can examine.

**Comment by yate** [comment]
I'm not sure if you can actually retrieve the built apk. I think we can set it up to release to github though.  The link is https://travis-ci.org/grzegorznittner/chanu, you can get to it by clicking on the "build passing" image in the readme.

**Comment by johnarleyburns** [comment]
I see it, but I don't see where it puts the apk.  In the script it says
"chanu/app/bin/chanu-debug.apk" but there's no commit for it and I don't
see where to find the apk.   I want to give the link to the G+ group for
testing.

**Comment by yate** [comment]
I don't think there's any way to retrieve the apk from travis without setting up some type of deployment.  It doesn't commit the built apk back.  
http://docs.travis-ci.com/user/deployment/
probably to github http://docs.travis-ci.com/user/deployment/releases/

**Comment by grzegorznittner** [comment]
I'll try to set it up later today

**Comment by grzegorznittner** [comment]
Just tried to set it up using travis command line.
Somehow setup was successful but there is no release deployed. Will need to
look at it closely.
