### ISSUE TITLE
crashes on Android L

### ISSUE THREAD

**Issue by lyrakat** [grzegorznittner/chanu#433]
the app crashes when starting on Android l. This happens on my Nexus 5 running the preview, and my Nexus 9 running the final version.

**Comment by johnarleyburns** [comment]
try the new fdroid 2.0.4 version

**Comment by lyrakat** [comment]
still crashes on open

**Comment by johnarleyburns** [comment]
is this 2.0.4?  can you get a logcat?

**Comment by lyrakat** [comment]
How do I get a lotcat

**Comment by SlayerOrnstein** [comment]
Try catlog

**Comment by lyrakat** [comment]
https://dl.dropboxusercontent.com/u/27280974/chanu.txt

**Comment by yate** [comment]
LetterSpacingTextView was changed in 2.0.4. You must somehow be running 2.0.3 still.  Can you try running the 4channer-debug.apk in the 2.0.4 release on github

**Comment by lyrakat** [comment]
you were right. Somehow I managed to download the old version. I've updated and it seems to be working

**Comment by johnarleyburns** [comment]
As Mr. Burns would say, "excellent!"

**Comment by johnarleyburns** [comment]
Can you also play with screen rotation to check if its fixed?

**Comment by lyrakat** [comment]
Seems fine

**Comment by yate** [comment]
mark as closed?

**Comment by johnarleyburns** [comment]
Mark it zero! https://www.youtube.com/watch?v=P41gT4eicrE
