### ISSUE TITLE
New boards need added

### ISSUE THREAD

**Issue by mysteriomask** [grzegorznittner/chanu#452]
Some new boards such as /qa/ and /aco/ need to be added to the app.   Or create an option to be able to add a board on your own.

**Comment by johnarleyburns** [comment]
Yes we have that fix, but we're still working on getting it to build as it
caused a build error.

**Comment by Greznor** [comment]
What build error are you getting?

**Comment by johnarleyburns** [comment]
its the one on the Travis CI where the automated builds happen
