### ISSUE TITLE
Crashing when accessing /aco/ , /his/ and /qa/

### ISSUE THREAD

**Issue by mysteriomask** [grzegorznittner/chanu#456]
/aco/, /his/, and /qa/.  These are new boards on 4Chan.  I can find then when I look though the latest posts.  But when I click on them it causes chanu to crash.

**Comment by Greznor** [comment]
I'm working on adding the new boards and few other features. I'll do a pull request for the fix soon.

**Comment by johnarleyburns** [comment]
Enough people like it I think it's worth putting back on Google Play, but
we can't do it under my old user account or anything that says ChanApps.

**Comment by Greznor** [comment]
I'm going to do some testing on Monday and I should be ready for a pull request for a new branch.

If you need someone to put it back on the Play Store, I'll take the bait.

**Comment by Greznor** [comment]
I'm ready to do a pull request with the new boards. Can you create a new branch for a pull request? I don't want to over write the "ui-experimental" branch.

**Comment by johnarleyburns** [comment]
Uh, just test it and overwrite the ui-experimental, we'll only release once
it works.
