### ISSUE TITLE
Changing download folder problem and crashing

### ISSUE THREAD

**Issue by mysteriomask** [grzegorznittner/chanu#473]
It seems if I change the download folder for images from its default it gives me an error for download whenever I try to save a photo.  If I leave it at default though the folder and images seem to not be able to be found in the phone storage whenever I plug the phone into my computer .

Also the captcha doesn't work when they ask you to draw something.

Also the app seems to have developed a random restart issue.  I can get halfway down a thread and then it suddenly goes blank and starts back at the top of the thread.

Finally I am curious if this app is now a dead app or if it is still being worked on since there hasn't been an update for it in over a year.

**Comment by Greznor** [comment]
What version are you running and what phone do you have?

I use the app almost daily and don't have issues. 

The app is not quite dead. Ive seen the feature requests and started working on some but the family life ended my free time for now.

I'll make some time to push an update with the new SDK and whatever changes that I made later this weekend. It may resolve the issue.

**Comment by mysteriomask** [comment]
I'm running 2.0.15 the most current available on f droid .  My phone is HTC One m9 with most recent updates.  

I use it almost daily as well I just encountered the save issue today when changing the destination folder since I was trying to save stuff to a folder that I'd be able to find when I plug it into a comp.

I still think chanu is the best app that's available out of the chanu apps so I was just wondering if there were plans to update it any anymore.

I did find some other minor bugs and issues that I can't think of right now, but nothing that you can't work past.

**Comment by Greznor** [comment]
I have 2.0.18. Once I get into my office, I'll push those changes. I don't think F-Droid has the latest.  

Are you changing the folder to an external sdcard? I have an m8 and Chanu can't write to an external sdcard. Google can't make up their mind about external sdcard permissions.

**Comment by mysteriomask** [comment]
No.  I do have an sd card but I chose to integrate that card into the main HD so it acts like its just part of the normal hard drive.  If it is saving to the sd card I wouldn't know since its all under the same thing now.

**Comment by mysteriomask** [comment]
Question.  But is there a way to get the updates for chanu without going through fdroid?
