### ISSUE TITLE
Thumbnails API

### ISSUE THREAD

**Issue by ghost** [grzegorznittner/chanu#478]
`/app/src/main/java/com/chanapps/four/component/URLFormatComponent.java` needs to be updated according to https://github.com/4chan/4chan-API/commit/830712e172b62f2e0b0ff80cb4dffd826ac715a5

<hr/>

```java
public static final String CHAN_THUMBS_URL_FORMAT = "//t.4cdn.org/%s/thumb/%ds.jpg";
```
to 
```java
public static final String CHAN_THUMBS_URL_FORMAT = "//i.4cdn.org/%s/thumb/%ds.jpg";
```
<hr/>

Might be related to https://github.com/grzegorznittner/chanu/issues/476

**Comment by Greznor** [comment]
This has already been resolved in #476. The fix is in the pending pull request.

I posted a link to a release (version 2.0.26) with the fix in #476 until the merge is accepted.
