### ISSUE TITLE
Threads and boards are emptied without reason

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#5]
Very often when you go back from image view you get empty thread view. Probably it's caused by refresh performed in the background.
I'm redesigning fetch/parse services, so we can handle those operations in proper way.

**Comment by johnarleyburns** [comment]
what happens when you "go back" is actually you call the intent for that activity so it has to restart the loader.  If we had something like "service callback" so it would call the loader immediately upon service completion, maybe that would minimize the lag time.

**Comment by johnarleyburns** [comment]
changed so refresh only occurs when going into a thread the first time, not on return from image view.  there is a time delay because of the refreshing / loading or something.
