### ISSUE TITLE
Downloads should self-cancel after some period of time

### ISSUE THREAD

**Issue by johnarleyburns** [grzegorznittner/chanu#53]
Sometimes I notice when doing a download on a slow connection (mobile data) it will just hang there and never complete.  The problem is the download notification just hangs there for hours even when I come back on wifi.  Killing 4chan background process is the only way to get rid of it.

**Comment by grzegorznittner** [comment]
Download task is removed when you leave FullImageDownload screen.
I've added "Cancel Download" button so it should be more obvious how to cancel download now. I still need to implement redirection to thread view.

**Comment by johnarleyburns** [comment]
What do you mean by redirection?

**Comment by grzegorznittner** [comment]
Just to go to the thread screen, like back button does.
Not sure how do you do that.
