### ISSUE TITLE
Navigation to the referenced post

### ISSUE THREAD

**Issue by grzegorznittner** [grzegorznittner/chanu#6]
Sometimes people put references to other posts, would be nice if we can handle that properly.
eg.

> > 77345983
> > I think you missed the point

**Comment by johnarleyburns** [comment]
I've just introduced where when you "reply" to a post it auto inserts the

> > postno for reference, is this what you mean?

**Comment by grzegorznittner** [comment]
That's usefull too, but I thought about posts which contain postno in the text. Usually it refers to some previous post which is not that easy to identify (now we display postno on the grid so it's easier).
I thought about links to that post, it will only scroll page to the referenced item.

**Comment by johnarleyburns** [comment]
Also we should have navigation for posts _responding_ to this one, so let's say I'm on post no 57, and someone in 63 has >57 in their reply, they are replying to me, I want to see all the replies.  Idea is to highlight in the grid maybe?
